sudo: false
language: r
cache: 
  - packages
  - ccache

env:
  global:
    - _R_CHECK_TIMINGS_=0

addons:
  apt:
    packages:
     - ccache


before_install:
  - mkdir $HOME/.R && echo -e 'CXX_STD = CXX14\n\nVER=\nCCACHE=ccache\nCC=$(CCACHE) gcc$(VER) -std=gnu99\nCXX=$(CCACHE) g++$(VER)\nC11=$(CCACHE) g++$(VER)\nC14=$(CCACHE) g++$(VER)\nFC=$(CCACHE) gfortran$(VER)\nF77=$(CCACHE) gfortran$(VER)' > $HOME/.R/Makevars


warnings_are_errors: false




  